### PR TITLE
FIX: remove failing test from suite

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
@xhochy one of the tests in upstream fails (possibly randomly since it passed in staged). I am proposing to simply remove this test so that the feedstock registration pass. Let us know if this is not the right resolution

**Review by arjanz — APPROVED** [review]
Yes this is fine for now, I also experience this sometimes and I suspect it is a race condition in the subscription code. True async support is on its way in the next major release, so for now it can be ignored.

**Comment by arjanz** [comment]
@MementoRC Because these race conditions also caused occasional failure for py-substrate-interface, these checks are now also removed from main: https://github.com/polkascan/py-substrate-interface/commit/a95a079f6a07137e1cddfda0c38c32fd5d2a6fc9

**Comment by xhochy** [comment]
> @xhochy one of the tests in upstream fails (possibly randomly since it passed in staged). I am proposing to simply remove this test so that the feedstock registration pass. Let us know if this is not the right resolution

Yes, that is usually the way forward (and make sure to post an upstream bug in these cases).

**Pull request merged**
